local s=require'lstage.stage'
local sched=require'lstage.scheduler'

local stage3=s.new(function(...) 
	print('third',...)
end)
stage3:instantiate(10)
local stage=s.new(function(...) 
	print('first',self,stage3,...)
	local stage2=s.new(function(s1,...) 
		print('second',s1,...)
		s1:push(...)
	end)
	stage2:push(stage3,...)
end)
stage:push(24,"event",math.pi)
local t=sched:new_thread()
t:join(1)
print("timed out")
print(stage,"instances:",stage:instances())
print(stage3,"instances:",stage3:instances())
local n=stage3:free(10)
print(stage3,"destroyed:",n,stage3:instances())
t:rawkill()

